services:
  - type: web
    name: projectplayground
    env: python
    preDeployCommand: pip install --no-cache-dir -r requirements.txt
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
