preDeployCommand: pip install --no-cache-dir -r requirements.txt

services:
  - type: web
    name: projectplayground
    env: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    plan: free
